<?php
// data initialization
for($r=0;$r<$totrele;$r++){
  $rele_old[$r]=0;
  $rele[$r]=0;
  $rete_time[$r]=mytime_up();
}
for($j=0;$j<12;$j++)$maskin[$j]=pow(2,$j);
for($dev=0;$dev<$totkeydev;$dev++)$oldin[$dev]=65535;
for($i=0;$i<72;$i++){
  $key_last0[$i]=0.0;
  $key_last1[$i]=0.0;
  for($j=$totkeydev;$j>0;$j--)if($i>=$keybasefordev[$j])break;
  $keyassigneddev[$i]=$j;
}

// card initialization
for($dev=0;$dev<4;$dev++)fwrite($mysock[$dev],chr(0x42).chr(0x00),2);
usleep($mysleep);
for($dev=0;$dev<4;$dev++)fwrite($mysock[$dev],chr(0x45).chr(0x0f),2);
usleep($mysleep);
for($dev=0;$dev<4;$dev++)fwrite($mysock[$dev],chr(0x48).chr(0xff),2);
usleep($mysleep);
$mysock[6]=socket_create(AF_INET,SOCK_STREAM,SOL_TCP);
socket_connect($mysock[6],"10.0.0.32",5000);
$mysock[7]=socket_create(AF_INET,SOCK_STREAM,SOL_TCP);
socket_connect($mysock[7],"10.0.0.34",5000);
for($j=48;$j<56;$j++){
  $mymsg1="k0".chr($j+1)."=0;";
  socket_write($mysock[6],$mymsg1,strlen($mymsg1));
  socket_write($mysock[7],$mymsg1,strlen($mymsg1));
  usleep($mysleep);
}
socket_close($mysock[6]);
socket_close($mysock[7]);
for($dev=0;$dev<4;$dev++)fwrite($mysock[$dev],chr(0x43).chr(0x00),2);
usleep($mysleep);
for($dev=0;$dev<4;$dev++)fwrite($mysock[$dev],chr(0x46).chr(0x00),2);
usleep($mysleep);
for($dev=0;$dev<4;$dev++)fwrite($mysock[$dev],chr(0x4a).chr(0x00),2);
usleep($mysleep);
?>
